#!/system/bin/sh

PATH=$(dirname $0):$PATH

IP=198.96.90.35 PORT=8856

case $1 in
	start)
		pgrep udp2raw_arm >/dev/null && echo Udp2Raw client is running ! && exit 0
		iptables -D INPUT -s ${IP}/32 -p tcp -m tcp --sport ${PORT} -j DROP
		iptables -I INPUT -s ${IP}/32 -p tcp -m tcp --sport ${PORT} -j DROP
		udp2raw_arm -c -r${IP}:${PORT} -l0.0.0.0:22345 --raw-mode faketcp -kpasswd --log-level 3 --force-sock-buf 4096 --cipher-mode xor --auth-mode simple >/dev/null 2>&1 &
		echo Udp2Raw client is started !
	;;
	stop)
		pgrep udp2raw_arm >/dev/null || { echo Udp2Raw client is not running ! && exit 0; }
		iptables -D INPUT -s ${IP}/32 -p tcp -m tcp --sport ${PORT} -j DROP
		kill $(pgrep udp2raw_arm)
		echo Udp2Raw client is stoped !
	;;
	status)
		pgrep udp2raw_arm >/dev/null && echo Udp2Raw client is running ! || echo Udp2Raw client is not running !
	;;
esac

